{{- if .Values.cassandra.reset }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migrations.fullname" . }}-cassandra-reset
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"  # Run before migrations
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cassandra-reset
          image: cassandra:4.1
          command: ["cqlsh"]
          args: [
            "$(CASSANDRA_HOST)",
            "-u", "$(CASSANDRA_USERNAME)",
            "-p", "$(CASSANDRA_PASSWORD)",
            "-e", "DROP KEYSPACE IF EXISTS $(CASSANDRA_KEYSPACE);"
          ]
          env:
            - name: CASSANDRA_HOST
              value: "{{ .Values.cassandra.env.host }}"
            - name: CASSANDRA_PORT
              value: "{{ .Values.cassandra.env.port }}"
            - name: CASSANDRA_USERNAME
              value: "{{ .Values.cassandra.env.username }}"
            - name: CASSANDRA_PASSWORD
              value: "{{ .Values.cassandra.env.password }}"
            - name: CASSANDRA_KEYSPACE
              value: "{{ .Values.cassandra.env.keyspace }}"
{{- end }}
