apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-token
  namespace: airflow
  annotations:
    kubernetes.io/service-account.name: airflow
type: kubernetes.io/service-account-token
