image:
  repository: cyprienkelma/airflow-m1
  tag: latest
  pullPolicy: Always


executor: "KubernetesExecutor"

airflow:
  config:
    core:
      load_examples: false

  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: true
      repo: "https://github.com/CyprienKelma/Projet-M1.git"
      branch: pipeline-dev
      subPath: pipeline/dags
      rev: HEAD
      depth: 1
      wait: 5
      maxFailures: 1
      env :
        - name: GIT_SYNC_SUBMODULES
          value: "off"

  web:
    port: 8080

  workers:
    replicas: 1

  flower:
    enabled: true

  logs:
    persistence:
      enabled: false

  createUserJob:
    useHelmHooks: true

  serviceAccount:
    create: true

  rbac:
    create: true

  extraEnvs:
    - name: AIRFLOW__KUBERNETES__NAMESPACE
      value: airflow
    - name: GIT_SYNC_SUBMODULE
      value: "off"
