airflow:
  executor: "KubernetesExecutor"
  extraPipPackages:
    - "minio"
    - "duckdb"
    - "psycopg2-binary"
    - "pandas"
    - "apache-airflow-providers-cncf-kubernetes"

  config:
    core:
      load_examples: true
    webserver:
      enable_proxy_fix: "True"
      base_url: "https://rancher.bafbi.fr/api/v1/namespaces/airflow/services/http:airflow-webserver:8080/proxy"

  web:
    port: 8080

  workers:
    replicas: 1

  flower:
    enabled: true

  logs:
    persistence:
      enabled: false

  createUserJob:
    useHelmHooks: true

  serviceAccount:
    create: true

  rbac:
    create: true

  extraEnvs:
    - name: AIRFLOW__KUBERNETES__NAMESPACE
      value: airflow
    - name: GIT_SYNC_SUBMODULE
      value: "off"
    - name: PYTHONPATH
      value: /opt/airflow/dags/repo/pipeline/dags
    - name: AIRFLOW__WEBSERVER__BASE_URL
      value: "https://rancher.bafbi.fr/api/v1/namespaces/airflow/services/http:airflow-webserver:8080/proxy"
    - name: SCRIPT_NAME
      value: "/api/v1/namespaces/airflow/services/http:airflow-webserver:8080/proxy"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/CyprienKelma/Projet-M1.git"
    branch: "pipeline-dev"
    subPath: "pipeline/dags"
    rev: HEAD
    depth: 1
    wait: 10
    maxFailures: 10
    env:
      - name: GIT_SYNC_SUBMODULES
        value: "off"

  persistence:
    enabled: false
