tenant:
  name: minio-tenant
  namespace: minio-tenant

  users:
    - name: minio
      secretRef:
        name: minio-creds

  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      size: 5Gi
      storageClassName: local-path

  mountPath: /export
  requestAutoCert: true
