apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spark
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps"]
    verbs: ["create", "get", "watch", "list", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["create", "get", "watch", "list", "delete"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-role-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
