apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "test-app.fullname" . }}
  annotations:
    config-hash: "{{ include "test-app.configHash" . }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "test-app.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: test-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
