apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: bronze-to-silver-demo
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: your-spark-image:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/bronze_to_silver.py
  sparkVersion: "3.4.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    labels:
      version: 3.4.1
  executor:
    cores: 1
    instances: 1
    memory: 1g
