apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.1.3"
    datacenters:
      - metadata:
          name: dc1
        size: 1
    softPodAntiAffinity: true
    # Resources must be specified for each Cassandra node when using softPodAntiAffinity
    resources:
      requests:
        cpu: 1200m
        memory: 1.5Gi
      limits:
        cpu: 2400m
        memory: 2.5Gi
    # It is also recommended to set the JVM heap size
    # config:
    #   jvmOptions:
    #     heap_initial_size: 1G
    #     heap_max_size: 1G
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
