apiVersion: v1
kind: Pod
metadata:
  name: test-spark
  namespace: spark
spec:
  containers:
    - name: spark
      image: apache/spark-py:v3.4.0
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: script-volume
          mountPath: /opt/spark/scripts
  volumes:
    - name: script-volume
      configMap:
        name: bronze-to-silver-script
  restartPolicy: Never
