apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apply-k8c1
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["k8ssandra.io"]
    resources: ["k8ssandraclusters"]
    verbs: ["get", "create", "update", "patch", "list"]
