apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.1.3"
    serverType: cassandra
    datacenters:
      - metadata:
          name: dc1
        size: 2
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
        config:
          jvmOptions:
            heapSize: 768M
    softPodAntiAffinity: true
    resources:
        requests:
          cpu: 300m
          memory: 1.5Gi
        limits:
          cpu: 600m
          memory: 2.5Gi
        # stargate:
        #   size: 1
        #   heapSize: 256M
        #   affinity:
        #     podAntiAffinity: null
